export const cards = [
    { value: "0", color: "blue", points: 0, ab: a },
    { value: "0", color: "blue", points: 0, ab: b },
    { value: "0", color: "green", points: 0, ab: a },
    { value: "0", color: "green", points: 0, ab: b },
    { value: "0", color: "red", points: 0, ab: a },
    { value: "0", color: "red", points: 0, ab, b },
    { value: "0", color: "yellow", points: 0, ab: a },
    { value: "0", color: "yellow", points: 0, ab: b },
    { value: "1", color: "blue", points: 1, ab: a },
    { value: "1", color: "blue", points: 1, ab: b },
    { value: "1", color: "green", points: 1, ab: a },
    { value: "1", color: "green", points: 1, ab: b },
    { value: "1", color: "red", points: 1, ab: a },
    { value: "1", color: "red", points: 1, ab: b },
    { value: "1",  color: "yellow",  points: 1, ab: a },
    { value: "1",  color: "yellow",  points: 1, ab: b },
    { value: "2", color: "blue", points: 2, ab: a },
    { value: "2", color: "blue", points: 2, ab: b },
    { value: "2",  color: "green",  points: 2, ab: a },
    { value: "2",  color: "green",  points: 2, ab: b },
    { value: "2", color: "red", points: 2, ab: a },
    { value: "2", color: "red", points: 2, ab: b},
    { value: "2", color: "yellow", points: 2, ab: a },
    { value: "2", color: "yellow", points: 2, ab: b },
    { value: "3", color: "blue", points: 3, ab: a },
    { value: "3", color: "blue", points: 3, ab: b },
    { value: "3", color: "green", points: 3, ab: a },
    { value: "3", color: "green", points: 3, ab: b },
    { value: "3", color: "red", points: 3, ab: a },
    { value: "3", color: "red", points: 3, ab: b },
    { value: "3", color: "yellow", points: 3, ab: a },
    { value: "3", color: "yellow", points: 3, ab: b },
    { value: "4", color: "blue", points: 4, ab: a },
    { value: "4", color: "blue", points: 4, ab: b },
    { value: "4", color: "green", points: 4, ab: a },
    { value: "4", color: "green", points: 4, ab: b },
    { value: "4", color: "red", points: 4, ab: a },
    { value: "4", color: "red", points: 4, ab: b },
    { value: "4", color: "yellow", points: 4, ab: a },
    { value: "4", color: "yellow", points: 4, ab: b },
    { value: "5", color: "blue", points: 5, ab: a },
    { value: "5", color: "blue", points: 5, ab: b },
    { value: "5", color: "green", points: 5, ab: a },
    { value: "5", color: "green", points: 5, ab: b },
    { value: "5", color: "red", points: 5, ab: a },
    { value: "5", color: "red", points: 5, ab: b },
    { value: "5", color: "yellow", points: 5, ab: a },
    { value: "5", color: "yellow", points: 5, ab: b },
    { value: "6", color: "blue", points: 6, ab: a },
    { value: "6", color: "blue", points: 6, ab: b },
    { value: "6", color: "green", points: 6, ab: a },
    { value: "6", color: "green", points: 6, ab: b },
    { value: "6", color: "red", points: 6, ab: a },
    { value: "6", color: "red", points: 6, ab: b },
    { value: "6", color: "yellow", points: 6, ab: a },
    { value: "6", color: "yellow", points: 6, ab: b },
    { value: "7" , color: "blue", points: 7, ab: a },
    { value: "7" , color: "blue", points: 7, ab: b },
    { value: "7" , color: "green", points: 7, ab: a },
    { value: "7" , color: "green", points: 7, ab: b },
    { value: "7",  color: "red",  points: 7, ab: a },
    { value: "7",  color: "red",  points: 7, ab: b },
    { value: "7", color: "yellow", points: 7, ab: a },
    { value: "7", color: "yellow", points: 7, ab: b },
    { value: "8", color: "blue", points: 8, ab: a },
    { value: "8", color: "blue", points: 8, ab: b },
    { value: "8", color: "green", points: 8, ab: a},
    { value: "8", color: "green", points: 8, ab: b},
    { value: "8", color: "red", points: 8, ab: a },
    { value: "8", color: "red", points: 8, ab: b },
    { value: "8", color: "yellow", points: 8, ab: a },
    { value: "8", color: "yellow", points: 8, ab: b },
    { value: "9", color: "blue", points: 9, ab: a },
    { value: "9", color: "blue", points: 9, ab: b },
    { value: "9", color: "green", points: 9, ab: a },
    { value: "9", color: "green", points: 9, ab: b },
    { value: "9", color: "red", points: 9, ab: a },
    { value: "9", color: "red", points: 9, ab: b },
    { value: "9", color: "yellow", points: 9, ab: a},
    { value: "9", color: "yellow", points: 9, ab: b },
    { value: "Draw Two", color: "blue", points: 20, ab: a },
    { value: "Draw Two", color: "blue", points: 20, ab: b },
    { value: "Draw Two", color: "green", points: 20, ab: a },
    { value: "Draw Two", color: "green", points: 20, ab: b },
    { value: "Draw Two", color: "red", points: 20, ab: a},
    { value: "Draw Two", color: "red", points: 20, ab: b},
    { value: "Draw Two", color: "yellow", points: 20, ab: a},
    { value: "Draw Two", color: "yellow", points: 20, ab: b},
    { value: "Reverse", color: "blue", points: 20, ab: a }
    { value: "Reverse", color: "blue", points: 20, ab: b },
    { value: "Reverse", color: "green", points: 20, ab: a },
    { value: "Reverse", color: "green", points: 20, ab: b },
    { value: "Reverse", color: "red", points: 20, ab: a },
    { value: "Reverse", color: "red", points: 20, ab: b },
    { value: "Reverse", color: "yellow", points: 20, ab: a },
    { value: "Reverse", color: "yellow", points: 20, ab: b },
    { value: "Skip", color: "blue", points: 20, ab: a },
    { value: "Skip", color: "blue", points: 20, ab: b },
    { value: "Skip", color: "green", points: 20, ab: a },
    { value: "Skip", color: "green", points: 20, ab: b },
    { value: "Skip", color: "red", points: 20, ab: a },
    { value: "Skip", color: "red", points: 20, ab: b },  
    { value: "Skip", color: "yellow", points: 20, ab: a },
    { value: "Skip", color: "yellow", points: 20, ab: b },
    { value: "Wild", color: "black", points: 50, ab: a },
    { value: "Wild", color: "black", points: 50, ab: b },
    { value: "Wild", color: "black", points: 50, ab: c },
    { value: "Wild", color: "black", points: 50, ab: d },
    { value: "Wild Draw Four", color: "black", points: 50, ab: a },
    { value: "Wild Draw Four", color: "black", points: 50, ab: b },
    { value: "Wild Draw Four", color: "black", points: 50, ab: c },
    { value: "Wild Draw Four", color: "black", points: 50, ab: d },
  ];